//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeilaoFabrica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoFornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutoFornecedor()
        {
            this.Leilaos = new HashSet<Leilao>();
        }
    
        public int Id { get; set; }
        public int Quantidade { get; set; }
        public int Id_Produto { get; set; }
        public int Id_Fornecedor { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leilao> Leilaos { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
